### PR TITLE
Running a local server using gulp-live-server

### PR DESCRIPTION
**Pull request by lelinhtinh**
## Update package.json
- Add script `gulp`. Using:

```
$ npm run gulp
```

Because `gulp` command does not work for me.
- Add `gulp-live-server` to run a local webserver.
## Update gulpfile.js
- Use Uglify's `ascii_only` to avoid converting UTF-8 escapes.
- Using `gulp-live-server`, folder **build** serving at [http://localhost:8888](http://localhost:8888)

### CODE REVIEW

**Comment by whatnickcodes** [comment]
Okay I like this but it messes with the drop in approach of this. Aka if you dropped this into an existing project that isn't stand alone.

Why don't you just make this so we can still do:

```
gulp (default) => watch files
gulp watch => watch files
gulp server => serve files
```

**Comment by lelinhtinh** [comment]
I rewrote it:
**gulp** (default) => watch files
**gulp server** => local server + watch files

``` js
// Load Gulp
var gulp = require('gulp'),
    gutil = require('gulp-util'),
    plugins = require('gulp-load-plugins')({
        rename: {
            'gulp-live-server': 'serve'
        }
    });

// Start Watching: Run "gulp"
gulp.task('default', ['watch']);

// Run "gulp server"
gulp.task('server', ['serve', 'watch']);

// Minify jQuery Plugins: Run manually with: "gulp squish-jquery"
gulp.task('squish-jquery', function () {
    return gulp.src('assets/js/libs/**/*.js')
        .pipe(plugins.uglify({
            output: {
                'ascii_only': true
            }
        }))
        .pipe(plugins.concat('jquery.plugins.min.js'))
        .pipe(gulp.dest('build'));
});

// Minify Custom JS: Run manually with: "gulp build-js"
gulp.task('build-js', function () {
    return gulp.src('assets/js/*.js')
        .pipe(plugins.jshint())
        .pipe(plugins.jshint.reporter('jshint-stylish'))
        .pipe(plugins.uglify({
            output: {
                'ascii_only': true
            }
        }))
        .pipe(plugins.concat('scripts.min.js'))
        .pipe(gulp.dest('build'));
});

// Less to CSS: Run manually with: "gulp build-css"
gulp.task('build-css', function () {
    return gulp.src('assets/less/*.less')
        .pipe(plugins.plumber())
        .pipe(plugins.less())
        .on('error', function (err) {
            gutil.log(err);
            this.emit('end');
        })
        .pipe(plugins.autoprefixer({
            browsers: [
                    '> 1%',
                    'last 2 versions',
                    'firefox >= 4',
                    'safari 7',
                    'safari 8',
                    'IE 8',
                    'IE 9',
                    'IE 10',
                    'IE 11'
                ],
            cascade: false
        }))
        .pipe(plugins.cssmin())
        .pipe(gulp.dest('build')).on('error', gutil.log);
});

// Default task
gulp.task('watch', function () {
    gulp.watch('assets/js/libs/**/*.js', ['squish-jquery']);
    gulp.watch('assets/js/*.js', ['build-js']);
    gulp.watch('assets/less/**/*.less', ['build-css']);
});

// Folder "build" serving at http://localhost:8888
// Should use Livereload (http://livereload.com/extensions/)
gulp.task('serve', function () {
    var server = plugins.serve.static('build', 8888);
    server.start();
    gulp.watch(['assets/less/**/*.less', 'assets/js/*.js', 'assets/js/libs/**/*.js'], function (file) {
        server.notify.apply(server, [file]);
    });
});
```

**Comment by whatnickcodes** [comment]
http://i.imgur.com/hMrjbdh.png

?

Also can you update the README with the request

**Comment by lelinhtinh** [comment]
**http://localhost:8888/** = Folder **build**

It's here:

```
http://localhost:8888/style.css
http://localhost:8888/scripts.min.js
http://localhost:8888/jquery.plugins.min.js
```

**Comment by whatnickcodes** [comment]
Oh shouldn't it be the other way around? 

http://localhost:8888/build/*

**Comment by lelinhtinh** [comment]
I thought just the build folder.

You can change `plugins.serve.static('build', 8888)` to `plugins.serve.static('/', 8888)`

**Comment by whatnickcodes** [comment]
Yeah this is awesome. But I think the purpose of a server built into this would be so you can just

```
git clone https://github.com/scotch-io/gulp-and-less-starter-kit
cd gulp-and-less-starter-kit
npm install
gulp serve
## then just visit the URL to start coding away
```

**Comment by whatnickcodes** [comment]
Awesome merging. Thanks! Really nice

**Comment by whatnickcodes** [comment]
Also I credited you in the README

**Comment by lelinhtinh** [comment]
Thank you. I've started using gulp and less from your repo. It has helped my work very much.

**Pull request merged**
